### PR TITLE
Check if _flatpickr object was initialized before trying to use setDateFromInput

### PR DESCRIPTION
**Pull request by magedhennawy**
Was getting initialization errors when trying to use pre selected ranged dates.

### CODE REVIEW

**Comment by magedhennawy** [comment]
@mezoistvan ping!

**Comment by mezoistvan** [comment]
Whoops, thanks for the ping and for the PR! I'll merge and release it this weekend.

**Comment by dockleryxk** [comment]
Why not just one if statement? For example 
```typescript
if ( this.flatpickrElement.nativeElement 
&& this.flatpickrElement.nativeElement._flatpickr 
&& changes.hasOwnProperty( 'setDate' ) 
&& changes[ 'setDate' ].currentValue ) {
... 
}
```

**Comment by magedhennawy** [comment]
@dockleryxk easy fix, it was an urgent hack, didnt sit through my mind for that long :p

**Comment by dockleryxk** [comment]
@magedhennawy I feel that! The compiler is maybe smart enough to optimize it anyway.

**Comment by mezoistvan** [comment]
I cleaned up the pr, and released in v7.0.2. Cheers! 👍

**Comment by magedhennawy** [comment]
Thank you! If you're curious as to what your project is used for, feel free to ping me @ magedhennawy@gmail.com

**Pull request merged**
