### PR TITLE
Add missing bind

### PR DESCRIPTION
**Pull request by msuntharesan**
The directive is missing the `.bind(this)` for `flatpickr` events.

### CODE REVIEW

**Comment by mezoistvan** [comment]
Could you please show and reproduce an error this PR fixes?

**Comment by vmcbaptista** [comment]
This should fix #77

**Comment by vmcbaptista** [comment]
@mezoistvan This is what is happening right now. When eventOnReady, eventOnOpen and eventOnClose, then this is not the instance of Ng2FlatpickrDirective, but some flatpickr related instance, see:
image

**Comment by mezoistvan** [comment]
@vmcbaptista @msuntharesan Thanks! I'll release this soon 🎆

**Comment by vmcbaptista** [comment]
Thanks @mezoistvan. Looking forward for that release 🙂

**Pull request merged**
