### PR TITLE
upgrade to angular 9

### PR DESCRIPTION
**Pull request by sgruhier**

### CODE REVIEW

**Comment by mezoistvan** [comment]
Thank you ! I'll review this in a few days. 💯

**Comment by peterbsmith2** [comment]
After attempting upgrading to Angular 9 today, I am unable to due to this PR being open and not merged.

**Comment by mezoistvan** [comment]
Published v9.0.0 which should work well. I incorporated these changes in the that commit, thank you very much @sgruhier!

**Comment by sgruhier** [comment]
My pleasure

**Pull request closed without merging**
