### PR TITLE
Expose flatpickr object

### PR DESCRIPTION
**Pull request by ly2xing**
Need to manually control flatpickr instance in some situations. since the flatpickr object is private in your wrapper component I added some methods to expose a couple methods from flatpickr.

### CODE REVIEW

**Comment by mezoistvan** [comment]
Hi, thanks for the PR! Unfortunately this is not a good way to handle this issue, because eventually this will lead to duplicating all the flatpickr methods in the component, which is way too much code and requires too much mainteance. Making the flatpickr object public is way more easier and more maintainable.

**Comment by ly2xing** [comment]
Updated the PR. Thanks!

**Comment by ly2xing** [comment]
@mezoistvan ping

**Comment by mezoistvan** [comment]
Thanks!

**Comment by mezoistvan** [comment]
Released in v7.0.3

**Pull request merged**
